apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-20T15:13:36Z"
  labels:
    run: nginx-pod
  name: nginx-pod
  namespace: user-1
  resourceVersion: "5989911"
  selfLink: /api/v1/namespaces/user-1/pods/nginx-pod
  uid: 24c96305-8d22-4d98-848e-17345ab3ef99
spec:
  containers:
  - image: fluentd
    imagePullPolicy: Always
    name: fluentd
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    volumeMounts:
    - name: log-volume
      mountPath: "/logs"
    - name: fluentd-config-volume
      mountPath: /fluentd/etc/fluentd.conf
      subPath: fluentd.conf
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ngdtg
      readOnly: true
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-conf-volume
      subPath: nginx.conf
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-esun-lecture-1-pool-4-4303c2db-zew5
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: log-volume
    emptyDir: {}
  - name: fluentd-config-volume
    configMap:
      name: fluentd-conf
  - name: nginx-conf-volume
    configMap:
      name: nginx-conf
  - name: default-token-ngdtg
    secret:
      defaultMode: 420
      secretName: default-token-ngdtg
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-20T15:13:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-20T15:13:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-20T15:13:38Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-20T15:13:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5343581ce02a0b161adf4049462cd183681929032ac5134f59b4157b049baeaf
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
    lastState: {}
    name: nginx-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-20T15:13:38Z"
  hostIP: 10.170.0.21
  phase: Running
  podIP: 10.60.1.47
  podIPs:
  - ip: 10.60.1.47
  qosClass: BestEffort
  startTime: "2021-01-20T15:13:36Z"
