apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2021-01-14T06:34:51Z"
    labels:
      run: nginx
    name: nginx
    namespace: user-16
    resourceVersion: "2832730"
    selfLink: /api/v1/namespaces/user-16/pods/nginx
    uid: 8207a415-b4db-42ea-8d1c-058fc664299b
  spec: 
    containers: 
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do echo $DUMMY_DATABASE_PASSWORD >> /html/index.html && sleep 5; done;" ]
      env:
        - name: DUMMY_DATABASE_PASSWORD
          value: admin
      volumeMounts:
        - mountPath: /html
          name: htmldir
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      # resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-zw5t9
        readOnly: true
      - mountPath: /usr/share/nginx/html
        name: htmldir
      livenessProbe: 
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      startupProbe:
        httpGet:
          path: /
          port: 80
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe: 
        tcpSocket:
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: gke-esun-lecture-1-pool-4-4303c2db-w4bd
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: htmldir
      emptyDir: {}
    - name: default-token-zw5t9
      secret:
        defaultMode: 420
        secretName: default-token-zw5t9
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T06:34:51Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T06:34:54Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T06:34:54Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T06:34:51Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://7b4fa0ed2c490c97ab90fe89aa9f8b56132951d194ef98497baf2ad83d79a23f
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2021-01-14T06:34:53Z"
    hostIP: 10.170.0.63
    phase: Running
    podIP: 10.60.5.15
    podIPs:
    - ip: 10.60.5.15
    qosClass: BestEffort
    startTime: "2021-01-14T06:34:51Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
